source "http://rubygems.org"
# Without any bound services, app runs on sqlite3
#.. but may also be staged with mysql

ruby "1.8.7"

gem 'mysql2'
gem 'mongo'
gem 'redis'
gem 'sinatra'
gem 'json'
gem 'carrot'
gem 'pg'
gem 'aws-s3'
gem "cf-autoconfig"