// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmware.appcloud.testapps.roo.guestbook.domain;

import java.lang.String;

privileged aspect Guest_Roo_JavaBean {
    
    public String Guest.getName() {
        return this.name;
    }
    
    public void Guest.setName(String name) {
        this.name = name;
    }
    
}
