// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmware.appcloud.testapps.roo.guestbook.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Guest_Roo_Configurable {
    
    declare @type: Guest: @Configurable;
    
}
