source "http://rubygems.org"
# Without any bound services, app runs on sqlite3
#.. but may also be staged with mysql
gem 'sinatra'
gem 'json'
gem 'pg'
gem 'mysql2'
gem 'bson_ext'
gem 'redis'
gem 'bunny'
gem 'mongo'
gem "yajl-ruby"
gem 'mysql2'
gem 'eventmachine'
gem 'mongo'
gem 'aws-s3'
