source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem "rake", "0.8.7"

# using oracle db
gem 'ruby-oci8', '~> 2.0.6'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.4.0'
gem 'ruby-plsql', '>=0.4.4'
