source :rubygems

gem "sinatra"
gem "rest-client"
gem "yajl-ruby"
gem "thin"
gem 'cf-uaa-client', :git => 'git://github.com/cloudfoundry/uaa.git', :ref => '1.2.5'
gem 'omniauth-uaa-oauth2', :git => 'git://github.com/cloudfoundry/omniauth-uaa-oauth2.git', :ref => 'd9f725091'


