source "https://rubygems.org"

gem "sinatra"

# Tested: ruby version
ruby "1.8.7"

# Tested: git based gem
gem "cf", :git => "http://github.com/cloudfoundry/cf.git", :ref => "9e802c"

# Tested: gem native ext
gem "ffi"
