test:
  adapter: sqlite3
  database: db/test.sqlite3
  encoding: utf8
development:
  adapter: sqlite3
  database: db/dev.sqlite3
  encoding: utf8
production:
  adapter: sqlite3
  database: db/prod.sqlite3
  encoding: utf8