source "http://rubygems.org"
# Without any bound services, app runs on sqlite3
#.. but may also be staged with mysql
gem 'mysql2'
gem 'mongo'
gem 'redis'
gem 'sinatra'
gem 'json_pure'
gem 'pg'
gem 'amqp'
